### ISSUE TITLE
New Logo for BadIPs.com

### ISSUE THREAD

**Issue by ybreza** [Ultimate-Hosts-Blacklist/BadIPs.com_KEY#1]
Hi There,
Can I contribute to donating a logo for your project?

**Comment by funilrys** [comment]
Hello @ybreza and welcome here!

May I ask which project are you talking about? 

Because this repository is only a wall between BadIPs.com data and our project which is [Ultimate.Hosts.Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist). 
Indeed, we use this repository to remove all inactive domains which are listed into BadIPs.com data with the help of [PyFunceble](https://github.com/funilrys/PyFunceble).


Thanks in advance for your clarification. 

Cheers,
Nissar

**Comment by ybreza** [comment]
Hi @funilrys 

Sorry I am less knowledgeable about this repository. but it looks like your project also does not have a logo yet.
I'm happy to donate logos, because I'm not adept in any code;)

If you agree I will be happy to contribute a donation logo for your project, or wherever you need;)

The last time I contributed a logo you can see [here](https://github.com/dwisiswant0/WiFiID/issues/2)

Regards

**Comment by funilrys** [comment]
Hi @ybreza thanks for your answer. 

I'm personally not against any proposal for [this](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist) project but it will have to be approved by at least me and @mitchellkrogza. 

If you have time you can also do some proposal for [this](https://github.com/funilrys/PyFunceble) or [this](https://github.com/dead-hosts) and maybe other in the future :smile_cat:.

**Comment by ybreza** [comment]
Thank you for your answer sir.
Looks like I'm happy to make a proposal for your project, [this one](https://github.com/funilrys/PyFunceble).

*Reza

**Comment by funilrys** [comment]
@ybreza Feel free to ask badipsTATAbadipsTODTODcom (TODTOD.= && TATA@=) for badips project.

______
Closing.
