### ISSUE TITLE
Line #1 0.0.0.0

### ISSUE THREAD

**Issue by spirillen** [Ultimate-Hosts-Blacklist/BadIPs.com_KEY#2]
https://hosts.ubuntu101.co.za/badips.txt

Line 1 > 
```
0.0.0.0
0.0.7.209
100.0.10.185
```

:smile:

**Comment by funilrys** [comment]
@spirillen In our central repository, everything is whitelisted by our whitelisting tool. So we do not distribute them.

**Comment by funilrys** [comment]
Also @spirillen, They are not present into `{clean,whitelisted}.list`.

**Comment by spirillen** [comment]
Hi @funilrys it was mostly a humorist note to https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/508#issuecomment-476374554 and https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/509#event-2227824277 :laughing:

**Comment by funilrys** [comment]
Hi @spirillen it was because of the migration from https://pypi.org/project/ultimate-hosts-blacklist-the-whitelist/ to https://pypi.org/project/ultimate-hosts-blacklist-whitelist/. Explanation about the differences can be found at https://github.com/Ultimate-Hosts-Blacklist/dev-center/issues/24#issuecomment-476409402 

Cheers,
Nissar
